name: gallery
description: A *booru client app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.4+18

environment:
  sdk: ">=3.3.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  convert: ^3.1.1

  photo_view:
    git:
      url: https://github.com/TheBigLettuce/photo_view.git
      ref: 0685380243233f9aa2e4b0d3c7b6534f7554f583

  path: ^1.8.3
  mime: ^1.0.4
  http_parser: ^4.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2
  transparent_image: ^2.0.0
  protobuf: ^3.0.0
  file_picker: ^5.2.10
  permission_handler: ^11.0.1
  introduction_screen: ^3.1.7
  analyzer: ^5.10.0
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^16.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.14
  chewie: ^1.5.0
  video_player: ^2.6.1
  html_unescape: ^2.0.0
  flutter_animate: ^4.1.1+1
  async: ^2.11.0
  dio: ^5.1.2
  logging: ^1.1.1
  dbus: ^0.7.8
  #google_fonts: ^4.0.4
  url_launcher: ^6.1.11
  intl: any
  palette_generator: ^0.3.3+2
  dio_cookie_manager: ^3.1.0
  cookie_jar: ^4.0.5
  wakelock_plus: ^1.1.1
  package_info_plus: ^4.1.0
  xml: ^6.3.0
  dynamic_color: ^1.6.7
  qr_flutter: ^4.1.0
  qrscan: ^0.3.3
  stream_transform: ^2.1.0
  stream_channel: ^2.1.2
  meta: ^1.11.0
  jikan_api: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_markdown: ^0.6.19
  local_auth: ^2.2.0
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  pigeon: ^12.0.1
  build_runner: ^2.4.1

  flutter_localizations:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: ZenKurenaido
      fonts:
        - asset: fonts/ZenKurenaido-Regular.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
